# Generated by Django 4.0.6 on 2022-08-09 02:21

import app.submissions.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import utils.django.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_code', models.TextField(verbose_name='source code')),
                ('solved', models.DateField(verbose_name='solved')),
                ('snapshot', models.ImageField(upload_to=app.submissions.models.snapshot_upload_path, verbose_name='snapshot')),
                ('runtime', models.CharField(blank=True, help_text='262 ms', max_length=32, null=True, verbose_name='runtime')),
                ('memory', models.CharField(blank=True, help_text='19 MB', max_length=32, null=True, verbose_name='memory')),
                ('runtime_rating', models.FloatField(blank=True, help_text='69.65% --> 0.6965', null=True, verbose_name='runtime rating')),
                ('memory_rating', models.FloatField(blank=True, help_text='54.09% --> 0.5409', null=True, verbose_name='memory rating')),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, help_text='1 is very easy, 5 is very hard.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='difficulty')),
                ('verify_status', models.CharField(choices=[('accepted', 'Accepted'), ('waiting', 'Waiting'), ('rejected', 'Rejected')], default='waiting', editable=False, max_length=32, verbose_name='verify status')),
                ('verified', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='verified')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='courses.course', verbose_name='course')),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='problems.language', verbose_name='lang')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='problems.question', verbose_name='question')),
                ('updater', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updater')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('verifier', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='verifier')),
            ],
            options={
                'verbose_name': 'submission',
                'verbose_name_plural': 'submissions',
            },
            managers=[
                ('objects', utils.django.managers.BaseManager()),
            ],
        ),
    ]
